/* Guía Roma · 15–19 sep 2026 · datos estructurados */
const MAPS = {
  home: "https://www.google.com/maps/search/?api=1&query=Via+dei+Capocci+86+Roma",
  search: (q) =>
    `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q + ", Roma")}`,
};

const GUIDE = {
  meta: {
    title: "Roma",
    dates: "15–19 sep 2026",
    homeAddress: "Via dei Capocci, 86",
    homeMaps: MAPS.home,
  },

  flights: {
    outbound: {
      date: "15 sep 2026",
      label: "Ida",
      from: "VAL",
      to: "ROM",
      dep: "15:25",
      arr: "17:30",
      summary: "VAL 15:25 → ROM 17:30",
    },
    return: {
      date: "19 sep 2026",
      label: "Vuelta",
      from: "ROM",
      to: "VAL",
      dep: "12:35",
      arr: "14:45",
      summary: "ROM 12:35 → VAL 14:45",
    },
  },

  access: {
    unlockPin: "4933",
    building: {
      title: "Puerta principal del edificio",
      code: "2436",
      steps: [
        "Escribe el código",
        "Pulsa la tecla de la llave 🔑",
        "Gira la manilla y abre la puerta",
      ],
    },
    apartment: {
      title: "Apartamento",
      number: "5",
      where: "Primer piso, puerta de la izquierda",
      code: "2588",
    },
  },

  starLegend: [
    { level: 3, label: "IMPRESCINDIBLE", desc: "Intentaría verlo sí o sí." },
    { level: 2, label: "MUY RECOMENDABLE", desc: "Merece mucho la pena, pero se puede sacrificar." },
    { level: 1, label: "SI CUADRA", desc: "Está bien si pasáis por allí o sobra tiempo." },
    { level: 0, label: "OPCIONAL", desc: "Visita de pago o extra solo si os apetece." },
  ],

  tickets: [
    {
      name: "Coliseo",
      status: "comprada",
      when: "Mié 16 sep, 17:00",
      booked: true,
      at: "2026-09-16T17:00:00",
      arriveEarlyMin: 20,
      dayId: "miercoles",
    },
    {
      name: "Museos Vaticanos + Capilla Sixtina",
      status: "comprada",
      when: "Jue 17 sep, 12:30",
      note: "Visita guiada en italiano",
      booked: true,
      at: "2026-09-17T12:30:00",
      arriveEarlyMin: 15,
      dayId: "jueves",
    },
    {
      name: "Castel Sant'Angelo",
      status: "comprada",
      when: "Jue 17 sep, 17:15",
      booked: true,
      at: "2026-09-17T17:15:00",
      arriveEarlyMin: 15,
      dayId: "jueves",
    },
    {
      name: "Panteón",
      status: "comprada",
      when: "Vie 18 sep, 09:00–10:00",
      booked: true,
      at: "2026-09-18T09:00:00",
      arriveEarlyMin: 15,
      dayId: "viernes",
    },
    { name: "Ara Pacis", status: "opcional / pendiente", when: "~10–13 €", booked: false },
  ],

  pocketKit: {
    weather: "Septiembre: ~22–28 ºC. Llevar agua; el centro es a pie y hay mucho sol.",
    emergencies: [
      { label: "Emergencias UE", value: "112", href: "tel:112" },
      { label: "Carabinieri", value: "112", href: "tel:112" },
      { label: "Ambulancia", value: "118", href: "tel:118" },
    ],
    items: [
      {
        title: "Vestimenta iglesias / Vaticano",
        text: "Hombros y rodillas cubiertos. Si no, os pueden denegar la entrada.",
      },
      {
        title: "Monedas",
        text: "Llevad monedas sueltas para la luz de los Caravaggios en San Luigi dei Francesi.",
      },
      {
        title: "Coliseo — mochila",
        text: "Sin mochilas grandes (+30×30 cm). Llegad 15–20 min antes de la hora reservada.",
      },
      {
        title: "Agua (nasoni)",
        text: "Roma tiene fuentes potables gratis. Llevad botella y rellenad. App: Nasoni / Drinking Fountains.",
      },
      {
        title: "Farmacia / Tabacchi cerca de casa",
        text: "En Monti, alrededor de Via Cavour y Via Nazionale hay farmacias y tabacchi (billetes ATAC a veces).",
      },
      {
        title: "Foro — última entrada",
        text: "Foro/Palatino: última entrada 18:15 (cierra 19:15 en septiembre).",
      },
    ],
    pharmacyMaps: "https://www.google.com/maps/search/?api=1&query=farmacia+near+Via+dei+Capocci+86+Roma",
  },

  foroNote:
    "Foro Romano y Palatino son UN SOLO recinto (PArCo): una sola validación de entrada y os movéis dentro entre ambos sin salir a la calle. No fiarse solo de la distancia en Maps: el recinto es grande y la puerta de SALIDA sí condiciona el siguiente tramo. Abre 09:00, cierra 19:15 (última entrada 18:15).",

  days: [
    {
      id: "martes",
      shortLabel: "Mar",
      label: "Martes 15",
      subtitle: "Llegada y Monti",
      note: "Día ligero. Si vais cansados, cena + paseo corto y listo.",
      foodDayKey: "martes",
      sections: [
        {
          id: "tarde-noche",
          label: "Tarde y noche",
          stops: [
            {
              id: "aterrizaje",
              time: "17:30",
              title: "Aterrizaje en Roma",
              stars: 0,
              note: "Vuelo VAL 15:25 → ROM 17:30. Leonardo Express recomendado: tren 18:08 Fiumicino → Termini 18:40 → casa ~18:51.",
            },
            {
              id: "alojamiento",
              time: "19:00",
              title: "Llegada al alojamiento en Monti",
              stars: 0,
              mapsUrl: MAPS.home,
              note: "Via dei Capocci, 86. Apartamento 5 (códigos de acceso en Inicio, protegidos).",
            },
            {
              id: "cena-monti",
              time: "20:00",
              title: "Cena en Monti",
              stars: 0,
              note: "Ver opciones en pestaña Comer · Restaurantes.",
            },
            {
              id: "piazza-madonna-monti",
              time: "21:00",
              title: "Piazza della Madonna dei Monti",
              stars: 2,
              duration: "10 min",
              walk: "5 min desde la cena",
              mapsUrl: MAPS.search("Piazza della Madonna dei Monti"),
              note: "Plaza con fuente; la gente se sienta a charlar por la noche.",
            },
            {
              id: "coliseo-exterior",
              time: "21:30",
              title: "Coliseo iluminado (exterior)",
              stars: 3,
              duration: "15–20 min",
              walk: "7–8 min, ~600 m desde Piazza Madonna dei Monti",
              mapsUrl: MAPS.search("Colosseo Roma"),
              note: "Solo desde fuera.",
              lookFor: [
                {
                  title: "Numerales de acceso",
                  text: "Los numerales romanos grabados sobre algunos arcos, que organizaban la entrada de 50.000 espectadores como un estadio moderno.",
                },
                {
                  title: "Marcas de los herrajes",
                  text: "El «efecto queso suizo» de la fachada: miles de agujeros de la Edad Media al extraer abrazaderas de hierro y bronce.",
                },
              ],
            },
            {
              id: "arco-constantino",
              time: "21:45",
              title: "Arco de Constantino",
              stars: 2,
              duration: "5–10 min",
              walk: "2–3 min, junto al Coliseo",
              mapsUrl: MAPS.search("Arco di Costantino Roma"),
              note: "Arco triunfal del siglo IV; de noche iluminado y sin gente.",
            },
          ],
        },
      ],
    },
    {
      id: "miercoles",
      shortLabel: "Mié",
      label: "Miércoles 16",
      subtitle: "Antigua Roma",
      note: "Prioridad: Foro+Palatino (un solo recinto: subir Palatino y bajar al Foro sin salir) y después Foros Imperiales, Trajano, Piazza Venezia y Campidoglio. Horario orientativo: si el recinto se alarga, se mueve todo lo demás.",
      foodDayKey: "miercoles",
      foodWarning:
        "Entrada al Coliseo a las 17:00. Si coméis en Testaccio o Campo de' Fiori, margen de vuelta — ideal comer ~13:30.",
      sections: [
        {
          id: "manana",
          label: "Mañana",
          stops: [
            {
              id: "foro-palatino",
              time: "09:00",
              title: "Foro Romano + Palatino",
              stars: 3,
              duration: "09:00–11:30/12:00",
              ticket: true,
              entrance:
                "Mismo recinto, una sola entrada. Preferid Via di San Gregorio, 30 (Varco Vignola, junto al Arco de Constantino): entráis y subís primero al Palatino, luego bajáis al Foro por caminos internos — NO hay que salir ni entrar otra vez al Foro. Evitad Largo della Salara Vecchia (Via dei Fori Imperiali): más cola.",
              mapsUrl: MAPS.search("Foro Romano Via di San Gregorio 30"),
              note: "Centro político y religioso (Templo de Saturno, Vía Sacra, Casa de las Vestales); en el Palatino, palacios imperiales y vistas al Circo Massimo. Un solo ticket = Foro + Palatino juntos.",
              lookFor: [
                {
                  title: "Templo de Cástor y Pólux",
                  text: "Las tres columnas solitarias, uno de los iconos más fotogénicos del recinto.",
                },
                {
                  title: "Curia Iulia",
                  text: "Suelo original de mármol policromado. Las puertas de bronce son réplica: las originales están en San Juan de Letrán.",
                },
                {
                  title: "Templo de Antonino y Faustina",
                  text: "Canales profundos en lo alto de las columnas de mármol verde: huellas de las cuerdas con que en la Edad Media intentaron derribarlas con bueyes.",
                },
                {
                  title: "Mirador del Circo Massimo (Palatino)",
                  text: "Vista del Circo Massimo completo justo antes de bajar; es fácil pasarla por alto.",
                },
              ],
            },
            {
              id: "salida-recinto",
              time: "Al terminar",
              title: "Elegir salida del recinto",
              stars: 0,
              note: "Ya habéis visto Palatino y Foro dentro. Al salir, elegid la puerta que mejor os lleve a Foros Imperiales / Trajano / Venezia (p. ej. Fori Imperiali / Salara Vecchia o zona Arco de Tito). No asumir que la salida está a pocos metros del siguiente monumento.",
            },
            {
              id: "foros-imperiales",
              time: "11:45",
              title: "Foros Imperiales",
              stars: 3,
              duration: "15 min",
              free: true,
              walk: "Según la salida del Foro/Palatino — no asumir metros cortos",
              mapsUrl: MAPS.search("Fori Imperiali Via dei Fori Imperiali"),
              note: "Se ven desde la calle, gratis.",
            },
            {
              id: "columna-trajano",
              time: "12:00",
              title: "Columna de Trajano",
              stars: 3,
              duration: "5 min",
              walk: "De camino, 5 min",
              free: true,
              mapsUrl: MAPS.search("Colonna Traiana Roma"),
              note: "Relieves en espiral: guerras contra los dacios.",
            },
            {
              id: "piazza-venezia",
              time: "12:15",
              title: "Piazza Venezia",
              stars: 3,
              walk: "2 min de paso",
              mapsUrl: MAPS.search("Piazza Venezia Roma"),
            },
            {
              id: "altare-patria",
              time: "12:20",
              title: "Monumento a Víctor Manuel II / Altare della Patria",
              stars: 3,
              duration: "20–30 min",
              free: true,
              walk: "En la misma plaza",
              mapsUrl: MAPS.search("Altare della Patria Roma"),
              note: "Tumba del Soldado Desconocido; terraza intermedia gratis a pie. Terrazza delle Quadrighe (360°) requiere ascensor (~10 €).",
            },
            {
              id: "campidoglio",
              time: "12:45",
              title: "Campidoglio",
              stars: 2,
              duration: "15 min",
              walk: "Subiendo la Cordonata, 2 min",
              mapsUrl: MAPS.search("Piazza del Campidoglio Roma"),
              note: "Plaza de Miguel Ángel con réplica de Marco Aurelio.",
              lookFor: [
                {
                  title: "Estatua de Marco Aurelio",
                  text: "En la réplica del centro (y en la original del museo): el caballo no tiene estribos. Los romanos montaban con mantas o sillas rígidas; el estribo llegó a Europa siglos después.",
                },
              ],
            },
            {
              id: "cosmedin-opc",
              time: "(opcional)",
              title: "Santa Maria in Cosmedin + Bocca della Verità",
              stars: 2,
              optional: true,
              duration: "15–20 min",
              walk: "~10 min bajando al río",
              mapsUrl: MAPS.search("Bocca della Verità Roma"),
              note: "Cola para la foto puede sumar tiempo.",
            },
            {
              id: "circo-opc",
              time: "(opcional)",
              title: "Circo Massimo",
              stars: 1,
              optional: true,
              duration: "10 min",
              walk: "3 min",
              mapsUrl: MAPS.search("Circo Massimo Roma"),
            },
            {
              id: "buco-opc",
              time: "(opcional)",
              title: "Piazza dei Cavalieri di Malta + Buco della Serratura",
              stars: 1,
              optional: true,
              duration: "5–10 min",
              walk: "~10 min al Aventino",
              mapsUrl: MAPS.search("Buco della Serratura Roma"),
            },
            {
              id: "sabina-opc",
              time: "(opcional)",
              title: "Santa Sabina + Giardino degli Aranci",
              stars: 2,
              optional: true,
              duration: "20–30 min",
              walk: "2 min mismo entorno",
              mapsUrl: MAPS.search("Giardino degli Aranci Roma"),
              note: "Una de las mejores vistas gratuitas sobre el Tíber y San Pedro.",
            },
            {
              id: "comida-testaccio",
              time: "13:00",
              title: "Comida en Testaccio",
              stars: 2,
              walk: "10–15 min bajando del Aventino (si opcionales) o cerca de Piazza Venezia/Monti",
              note: "Helados y restaurantes en pestaña Comer.",
            },
          ],
        },
        {
          id: "tarde",
          label: "Tarde",
          stops: [
            {
              id: "descanso",
              time: "15:00",
              title: "Descanso en el alojamiento",
              stars: 3,
              duration: "15:00–16:30",
              mapsUrl: MAPS.home,
            },
            {
              id: "coliseo",
              time: "17:00",
              title: "Coliseo",
              stars: 3,
              duration: "17:00–18:30",
              ticket: true,
              entrance:
                "Sperone Valadier, lado noreste, frente metro Colosseo (B). Carril “Visitantes con reserva”. Llegar 15–20 min antes. Sin mochilas +30×30 cm.",
              mapsUrl: MAPS.search("Colosseo ingresso Sperone Valadier"),
              note: "Arena y gradas con entrada básica.",
              lookFor: [
                {
                  title: "Numerales de acceso",
                  text: "Numerales romanos en algunos arcos: organizaban la entrada de 50.000 espectadores como un estadio moderno.",
                },
                {
                  title: "Túnel de los muertos",
                  text: "Desde la arena, hacia los extremos del óvalo: Porta Libitinaria, por donde sacaban cuerpos de gladiadores y animales.",
                },
                {
                  title: "Laberinto del subsuelo",
                  text: "Mirad el Hipogeo desde la arena: anclajes y rieles de piedra de los 28 ascensores de madera que subían fieras con poleas.",
                },
                {
                  title: "Marcas de los herrajes",
                  text: "«Efecto queso suizo» en la fachada: agujeros medievales al picar la piedra para sacar abrazaderas de hierro y bronce.",
                },
                {
                  title: "Grafitis antiguos",
                  text: "En pasillos y barandillas: relieves del público con gladiadores, palmeras de victoria o tableros de juego.",
                },
              ],
            },
            {
              id: "san-pietro-vincoli",
              time: "Después Coliseo",
              title: "San Pietro in Vincoli",
              stars: 2,
              optional: true,
              duration: "10–15 min",
              mapsUrl: MAPS.search("San Pietro in Vincoli Moisés"),
              note: "Moisés de Miguel Ángel a la derecha del altar. O San Clemente en dirección opuesta — no las dos el mismo día.",
              lookFor: [
                {
                  title: "El Moisés de Miguel Ángel",
                  text: "A la derecha del altar. De perfil tiene «cuernos» por una mala traducción bíblica (rayos de luz → cuernos). En la rodilla derecha, una marca: la leyenda dice que Miguel Ángel la golpeó con el cincel gritando «¿Por qué no hablas?!».",
                },
              ],
            },
            {
              id: "san-clemente-opc",
              time: "Alternativa",
              title: "Basílica de San Clemente",
              stars: 2,
              optional: true,
              walk: "8–10 min, lado San Giovanni in Laterano",
              mapsUrl: MAPS.search("Basilica San Clemente Roma"),
              note: "Nivel inferior de pago (~10 €). Templo de Mitra y callejón subterráneo con agua.",
            },
            {
              id: "cena-monti-mie",
              time: "20:00",
              title: "Cena en Monti",
              stars: 0,
            },
          ],
        },
      ],
    },
    {
      id: "jueves",
      shortLabel: "Jue",
      label: "Jueves 17",
      subtitle: "Vaticano, Castel Sant'Angelo y Trastevere",
      note: "No meter más visitas importantes: las entradas marcan un ritmo ajustado.",
      foodDayKey: "jueves",
      sections: [
        {
          id: "dia",
          label: "Ruta",
          stops: [
            {
              id: "san-pedro",
              time: "08:00",
              title: "Plaza de San Pedro + Basílica de San Pedro",
              stars: 3,
              duration: "08:00–09:30",
              free: true,
              walk: "Desde casa: ~45–50 min andando / mejor metro ~30–35 min (B→Termini→A Ottaviano + 10 min)",
              mapsUrl: MAPS.search("Basilica San Pietro Roma"),
              note: "Piedad de Miguel Ángel; baldaquino de Bernini.",
              lookFor: [
                {
                  title: "Efecto óptico de Bernini (plaza)",
                  text: "Entre el obelisco y cada fuente, baldosa redonda «Centro del Colonnato»: parado encima, las cuatro filas de columnas se alinean en una sola.",
                },
                {
                  title: "Rosa de los vientos",
                  text: "Alrededor del obelisco, relieves de vientos. Buscad «Libeccio» (suroeste): se rumorea una marca de Miguel Ángel.",
                },
                {
                  title: "Baldaquino e interior",
                  text: "Columnas retorcidas de Bernini sobre el altar. En el suelo de la nave, marcas con el tamaño de otras catedrales del mundo.",
                },
              ],
            },
            {
              id: "borgo-pio",
              time: "09:30",
              title: "Borgo Pio / alrededores",
              stars: 1,
              duration: "09:30–11:30",
              walk: "5 min desde San Pedro",
              note: "Café y margen.",
            },
            {
              id: "encuentro-grupo",
              time: "12:00",
              title: "Encuentro con el grupo",
              stars: 0,
              duration: "12:00–12:15",
              walk: "15–20 min, ~1,3 km desde Borgo Pio rodeando murallas hasta Viale Vaticano",
              mapsUrl: MAPS.search("Musei Vaticani ingresso Viale Vaticano"),
            },
            {
              id: "vaticano",
              time: "12:30",
              title: "Museos Vaticanos + Capilla Sixtina",
              stars: 3,
              duration: "12:30–15:30",
              ticket: true,
              walk: "Tras el encuentro en la entrada",
              entrance: "Entrada única Viale Vaticano, 00120. Metro A Ottaviano, 8–10 min andando.",
              mapsUrl: MAPS.search("Musei Vaticani Viale Vaticano"),
              note: "Estancias de Rafael; Capilla Sixtina con techo y Juicio Final.",
              lookFor: [
                {
                  title: "Torso del Belvedere",
                  text: "Museo Pío-Clementino: torso sin cabeza ni brazos. Miguel Ángel no quiso «completarla» y copió su musculatura para el Jesús de la Sixtina.",
                },
                {
                  title: "Sala de los Animales",
                  text: "Zoo de mármol: colores naturales imitan piel, plumas y pelaje sin pintura.",
                },
                {
                  title: "Firma oculta de Rafael",
                  text: "En La Escuela de Atenas, Da Vinci es Platón y Miguel Ángel Heráclito. Rafael se autorretrató abajo a la derecha: joven con gorra negra mirando al público.",
                },
                {
                  title: "Ojos mágicos de los tapices",
                  text: "Galería de los Tapices: mirad los ojos de Jesús en la Resurrección y caminad despacio; la mirada parece seguiros.",
                },
                {
                  title: "Galería de los Mapas",
                  text: "El techo muestra milagros o santos de la región dibujada justo debajo en el mapa de la pared.",
                },
                {
                  title: "Capilla Sixtina",
                  text: "Techo: mano de Dios y Adán a punto de tocarse. Juicio Final: San Bartolomé con piel desollada — esa cara es autorretrato de Miguel Ángel.",
                },
                {
                  title: "Escalera de Bramante",
                  text: "Al salir: caracol doble (1932). Dos hélices independientes (subir/bajar) para que la gente no se cruce.",
                },
              ],
            },
            {
              id: "comida-borgo",
              time: "15:45",
              title: "Comida en Borgo Pio",
              stars: 2,
              duration: "15:45–16:45",
              walk: "15–20 min, ~1,3 km desde la salida de los museos",
              note: "Pastasciutta decidido — ver Comer.",
            },
            {
              id: "castel",
              time: "17:15",
              title: "Castel Sant'Angelo",
              stars: 3,
              duration: "17:15–19:00",
              ticket: true,
              walk: "10–12 min, ~900 m desde Borgo Pio",
              entrance: "Lungotevere Castello, 50, junto al Ponte Sant'Angelo.",
              mapsUrl: MAPS.search("Castel Sant'Angelo Roma"),
              lookFor: [
                {
                  title: "El Passetto",
                  text: "Pasillo elevado de piedra que conecta el castillo con el Vaticano; visible desde varios puntos de la terraza.",
                },
                {
                  title: "Proyectiles defensivos",
                  text: "En patios superiores: enormes bolas de piedra, munición de catapultas y cañones papales en los asedios.",
                },
              ],
            },
            {
              id: "trastevere-paseo",
              time: "19:15",
              title: "Paseo por Trastevere",
              stars: 2,
              walk: "20–25 min, ~1,7 km cruzando el Tíber",
              mapsUrl: MAPS.search("Trastevere Roma"),
            },
            {
              id: "santa-maria-trastevere",
              time: "Trastevere",
              title: "Santa Maria in Trastevere",
              stars: 2,
              duration: "10–15 min",
              mapsUrl: MAPS.search("Santa Maria in Trastevere"),
              note: "Mosaicos dorados del siglo XII.",
            },
            {
              id: "santa-cecilia",
              time: "Trastevere",
              title: "Santa Cecilia in Trastevere",
              stars: 2,
              duration: "15–20 min",
              walk: "5 min desde Santa Maria in Trastevere",
              mapsUrl: MAPS.search("Santa Cecilia in Trastevere"),
            },
            {
              id: "gianicolo",
              time: "Atardecer",
              title: "Fontana dell'Acqua Paola / Gianicolo",
              stars: 2,
              duration: "20–30 min",
              walk: "15 min subiendo desde Trastevere",
              mapsUrl: MAPS.search("Terrazza del Gianicolo Roma"),
            },
            {
              id: "cena-trastevere",
              time: "20:00",
              title: "Cena en Trastevere",
              stars: 0,
            },
          ],
        },
      ],
    },
    {
      id: "viernes",
      shortLabel: "Vie",
      label: "Viernes 18",
      subtitle: "Centro histórico",
      foodDayKey: "viernes",
      sections: [
        {
          id: "manana",
          label: "Mañana — Panteón y entorno",
          stops: [
            {
              id: "santa-maria-maggiore-vie",
              time: "07:30",
              title: "Santa Maria Maggiore",
              stars: 3,
              optional: true,
              duration: "15–20 min",
              mapsUrl: MAPS.search("Basilica Santa Maria Maggiore Roma"),
              note: "OPCIONAL aquí; alternativa al sábado. Mosaicos del V; tumba de Bernini.",
              tip: "Horario orientativo lun–sáb ~08:00–18:30 (última entrada ~18:00). No la deis por hecha a las 20:00.",
            },
            {
              id: "pantheon",
              time: "09:00",
              title: "Panteón",
              stars: 3,
              duration: "09:00–10:00",
              ticket: true,
              walk: "~15–18 min, ~1,2 km desde Santa Maria Maggiore (~25–30 min / ~2 km desde casa)",
              entrance: "Piazza della Rotonda — la fachada con columnas es la entrada.",
              mapsUrl: MAPS.search("Pantheon Roma"),
              lookFor: [
                {
                  title: "Óculo y cúpula",
                  text: "Haz de luz por el óculo (único punto de luz natural; llueve dentro). Hormigón de la cúpula afinado hacia arriba para aligerar peso.",
                },
                {
                  title: "Desagües ocultos",
                  text: "En el suelo bajo el óculo: 22 agujeros de drenaje. El mármol está curvado para que el agua no inunde el templo.",
                },
              ],
            },
            {
              id: "sopra-minerva",
              time: "10:05",
              title: "Santa Maria sopra Minerva",
              stars: 2,
              duration: "10 min",
              walk: "1 min, justo detrás del Panteón",
              mapsUrl: MAPS.search("Santa Maria sopra Minerva Roma"),
              lookFor: [
                {
                  title: "Elefante travieso de Bernini",
                  text: "En la plaza: elefante con obelisco. Por detrás, le da el trasero al convento dominico — venganza de Bernini contra un monje que criticó su diseño.",
                },
              ],
            },
            {
              id: "san-luigi",
              time: "10:20",
              title: "San Luigi dei Francesi — Caravaggios",
              stars: 3,
              duration: "15–20 min",
              walk: "5 min, ~400 m desde Santa Maria sopra Minerva",
              mapsUrl: MAPS.search("San Luigi dei Francesi Roma"),
              note: "3 Caravaggios de San Mateo en la última capilla a la izquierda.",
              tip: "Llevad monedas sueltas: la luz de la capilla se enciende con monedas. Sin ellas apenas se ven los cuadros.",
            },
            {
              id: "navona",
              time: "10:45",
              title: "Piazza Navona",
              stars: 3,
              duration: "15 min",
              walk: "3 min, ~250 m desde San Luigi",
              mapsUrl: MAPS.search("Piazza Navona Roma"),
              lookFor: [
                {
                  title: "Fontana dei Quattro Fiumi",
                  text: "Río de la Plata con la mano levantada frente a la iglesia de Borromini. El Nilo lleva la cabeza velada: en el XVII aún no se sabía dónde nacía el río.",
                },
              ],
            },
            {
              id: "agnese",
              time: "11:00",
              title: "Sant'Agnese in Agone",
              stars: 2,
              optional: true,
              duration: "10 min",
              walk: "En la misma plaza",
              mapsUrl: MAPS.search("Sant'Agnese in Agone Roma"),
            },
            {
              id: "campo-fiori",
              time: "11:20",
              title: "Campo de' Fiori",
              stars: 1,
              duration: "10–15 min",
              walk: "8 min, ~600 m desde Piazza Navona",
              mapsUrl: MAPS.search("Campo de' Fiori Roma"),
            },
            {
              id: "farnese",
              time: "11:37",
              title: "Piazza Farnese",
              stars: 1,
              walk: "2 min desde Campo de' Fiori",
              mapsUrl: MAPS.search("Piazza Farnese Roma"),
            },
            {
              id: "barrio-judio",
              time: "11:45",
              title: "Barrio Judío / Portico d'Ottavia",
              stars: 2,
              duration: "15–20 min",
              walk: "8 min, ~600 m",
              mapsUrl: MAPS.search("Portico d'Ottavia Roma"),
            },
            {
              id: "tartarughe",
              time: "12:12",
              title: "Fontana delle Tartarughe",
              stars: 2,
              walk: "2 min desde el Portico d'Ottavia",
              mapsUrl: MAPS.search("Fontana delle Tartarughe Roma"),
            },
            {
              id: "isola-tiberina",
              time: "12:20",
              title: "Isola Tiberina + Ponte Fabricio",
              stars: 1,
              walk: "5 min desde la Fontana delle Tartarughe (ida y vuelta)",
              mapsUrl: MAPS.search("Isola Tiberina Roma"),
            },
            {
              id: "torre-argentina",
              time: "12:35",
              title: "Largo di Torre Argentina",
              stars: 1,
              duration: "10 min",
              walk: "5 min, ~400 m",
              mapsUrl: MAPS.search("Largo di Torre Argentina Roma"),
              note: "Aquí murió César; refugio de gatos.",
            },
            {
              id: "comida-judio",
              time: "12:55",
              title: "Comida en Barrio Judío / Campo de' Fiori",
              stars: 2,
              walk: "5 min",
            },
          ],
        },
        {
          id: "tarde",
          label: "Tarde — Barroco, Trevi y norte",
          stops: [
            {
              id: "gesu",
              time: "15:00",
              title: "Chiesa del Gesù",
              stars: 3,
              duration: "15 min",
              walk: "~8–10 min, ~700 m desde la zona de la comida",
              mapsUrl: MAPS.search("Chiesa del Gesù Roma"),
              tip: "Si queréis ver el cuadro del altar deslizarse y revelar la estatua de plata, intentad pasar ~17:30 (sujeto a horario del día).",
              lookFor: [
                {
                  title: "La pintura que se mueve",
                  text: "Techo: Triunfo del Nombre de Jesús. Si pasáis ~17:30, el cuadro del altar baja con poleas del XVII y revela una estatua de plata de San Ignacio iluminada.",
                },
              ],
            },
            {
              id: "sant-ignazio",
              time: "15:25",
              title: "Sant'Ignazio di Loyola",
              stars: 3,
              duration: "10–15 min",
              walk: "7–8 min, ~600 m desde el Gesù",
              mapsUrl: MAPS.search("Sant'Ignazio di Loyola Roma"),
              note: "Techo de Andrea Pozzo; mirar desde el disco en el suelo.",
              lookFor: [
                {
                  title: "La falsa cúpula",
                  text: "Pozzo pintó una cúpula 3D que es plana. Efecto perfecto: colocaos sobre el disco de mármol marcado en el suelo de la nave.",
                },
              ],
            },
            {
              id: "pietra",
              time: "15:42",
              title: "Piazza di Pietra (Templo de Adriano)",
              stars: 1,
              walk: "2–3 min desde Sant'Ignazio",
              mapsUrl: MAPS.search("Piazza di Pietra Roma"),
            },
            {
              id: "colonna-aurelio",
              time: "15:50",
              title: "Piazza Colonna / Columna de Marco Aurelio",
              stars: 2,
              walk: "3–4 min desde Piazza di Pietra",
              mapsUrl: MAPS.search("Colonna di Marco Aurelio Roma"),
            },
            {
              id: "trevi",
              time: "15:50",
              title: "Fontana di Trevi",
              stars: 3,
              duration: "15–20 min",
              walk: "~8–10 min, ~700 m desde Sant'Ignazio",
              mapsUrl: MAPS.search("Fontana di Trevi Roma"),
              note: "Tradición: moneda de espaldas.",
              lookFor: [
                {
                  title: "Jarrón de la venganza",
                  text: "A la derecha, en el muro exterior, un jarrón («as de copas»): Bernini lo puso para tapar la vista de la fuente a un barbero que criticaba su trabajo desde la tienda de detrás.",
                },
              ],
            },
            {
              id: "spagna",
              time: "16:20",
              title: "Piazza di Spagna",
              stars: 2,
              duration: "15 min",
              walk: "8 min, ~600 m desde Trevi",
              mapsUrl: MAPS.search("Piazza di Spagna Roma"),
            },
            {
              id: "popolo",
              time: "16:45",
              title: "Piazza del Popolo",
              stars: 2,
              duration: "15 min",
              walk: "10 min, ~900 m desde Piazza di Spagna",
              mapsUrl: MAPS.search("Piazza del Popolo Roma"),
            },
            {
              id: "santa-maria-popolo",
              time: "17:00",
              title: "Santa Maria del Popolo",
              stars: 3,
              duration: "15–20 min",
              walk: "En la misma plaza",
              mapsUrl: MAPS.search("Santa Maria del Popolo Caravaggio"),
              note: "Dos Caravaggios en Capilla Cerasi; Capilla Chigi de Rafael.",
            },
            {
              id: "ara-pacis",
              time: "17:30",
              title: "Ara Pacis",
              stars: 1,
              optional: true,
              duration: "30–45 min",
              walk: "10 min, ~800 m desde Piazza del Popolo",
              mapsUrl: MAPS.search("Ara Pacis Roma"),
              note: "OPCIONAL si sobra tiempo.",
            },
          ],
        },
      ],
    },
    {
      id: "sabado",
      shortLabel: "Sáb",
      label: "Sábado 19",
      subtitle: "Salida",
      note: "Tras Santa Maria Maggiore a las 8:00, ~1 h de margen en casa antes de salir a Termini — no entretenerse.",
      foodDayKey: "sabado",
      sections: [
        {
          id: "manana",
          label: "Mañana",
          stops: [
            {
              id: "manana-libre",
              time: "Mañana",
              title: "Mañana libre según vuelo",
              stars: 0,
              note: "Vuelo ROM 12:35 → VAL 14:45. Tren recomendado: salir casa ~09:10 → Termini 09:25 → tren 09:35 → Fiumicino 10:07.",
            },
            {
              id: "santa-maria-maggiore-sab",
              time: "08:00",
              title: "Santa Maria Maggiore",
              stars: 3,
              duration: "15–20 min",
              walk: "8–10 min desde Monti",
              mapsUrl: MAPS.search("Basilica Santa Maria Maggiore Roma"),
              note: "Si no la visteis el viernes. Abre ~7:00.",
              tip: "Última entrada ~18:00 (cierra ~18:30). El sábado solo tenéis ~1 h de margen en casa después — no entretenerse.",
            },
            {
              id: "monti-paseo",
              time: "Después",
              title: "Monti — último paseo",
              stars: 1,
              mapsUrl: MAPS.search("Rione Monti Roma"),
            },
            {
              id: "mercado-testaccio",
              time: "Si apetece",
              title: "Mercado de Testaccio",
              stars: 1,
              optional: true,
              mapsUrl: MAPS.search("Mercato di Testaccio Roma"),
            },
            {
              id: "repetir",
              time: "Opcional",
              title: "Repetir algún lugar favorito",
              stars: 1,
              optional: true,
            },
          ],
        },
      ],
    },
  ],

  food: {
    lists: [
      {
        id: "restaurants",
        label: "Restaurantes",
        desc: "Tu lista guardada en Google Maps",
        url: "https://maps.app.goo.gl/w1TK7MSDpxEKPfNR6",
      },
      {
        id: "gelato",
        label: "Helados y tiramisú",
        desc: "Tu lista guardada en Google Maps",
        url: "https://maps.app.goo.gl/rTpcxnvMctvXgwou8",
      },
      {
        id: "street",
        label: "Comida callejera",
        desc: "Tu lista guardada en Google Maps",
        url: "https://maps.app.goo.gl/cFHH8D82yhGwXckL7",
      },
    ],
    gelato: [
      {
        day: "martes",
        dayLabel: "Martes — Monti",
        name: "Fatamorgana",
        desc: "Sin lactosa y veganas; fruta de temporada.",
        address: "Piazza degli Zingari, 5",
        rating: 4.4,
        mapsUrl: "https://maps.google.com/?q=Fatamorgana+Piazza+degli+Zingari+Roma",
      },
      {
        day: "martes",
        dayLabel: "Martes — Monti",
        name: "Gelateria dell'Angeletto",
        desc: "Pequeña, artesanal, muy querida en el barrio.",
        address: "Via dell'Angeletto, 15",
        rating: 4.7,
        mapsUrl: MAPS.search("Gelateria dell'Angeletto Via dell'Angeletto 15"),
      },
      {
        day: "miercoles",
        dayLabel: "Miércoles — Testaccio",
        name: "Gelateria Brivido",
        desc: "Premiada; sabor al pino es la bandera.",
        address: "Via Giovanni Battista Bodoni, 62",
        rating: 4.7,
        mapsUrl: "https://maps.google.com/?q=Gelateria+Brivido+Roma",
      },
      {
        day: "jueves",
        dayLabel: "Jueves — Vaticano / Trastevere",
        name: "Gelateria dei Gracchi",
        desc: "De las mejores cerca del Vaticano.",
        address: "Via dei Gracchi, 272 (Prati)",
        rating: 4.6,
        mapsUrl: "https://maps.google.com/?q=Gelateria+dei+Gracchi+Prati+Roma",
      },
      {
        day: "jueves",
        dayLabel: "Jueves",
        name: "Gelateria del Teatro",
        desc: "Sabores originales (higo con almendra).",
        address: "Via dei Coronari, 65/66",
        rating: 4.5,
        mapsUrl: "https://maps.google.com/?q=Gelateria+del+Teatro+Via+dei+Coronari+Roma",
      },
      {
        day: "jueves",
        dayLabel: "Jueves — Trastevere",
        name: "Fior di Luna",
        desc: "Favorita de Trastevere; chocolate negro espectacular.",
        address: "Via della Lungaretta, 96",
        rating: 4.6,
        mapsUrl: "https://maps.google.com/?q=Fior+di+Luna+Trastevere+Roma",
      },
      {
        day: "viernes",
        dayLabel: "Viernes — Centro",
        name: "Giolitti",
        desc: "Institución desde 1900.",
        address: "Via degli Uffici del Vicario, 40",
        rating: 4.4,
        mapsUrl: "https://maps.google.com/?q=Giolitti+Via+degli+Uffici+del+Vicario+Roma",
      },
      {
        day: "viernes",
        dayLabel: "Viernes",
        name: "Two Sizes",
        desc: "Tiramisú viral en vasitos.",
        address: "Via del Governo Vecchio, 88",
        rating: 4.8,
        mapsUrl: "https://maps.google.com/?q=Two+Sizes+Roma",
      },
      {
        day: "viernes",
        dayLabel: "Viernes",
        name: "Pompi Tiramisù",
        desc: "Navona y Spagna.",
        address: "Via di Tor Millina, 33 / Via della Croce, 82",
        rating: 4.3,
        mapsUrl: "https://maps.google.com/?q=Pompi+Tiramisu+Roma",
      },
      {
        day: "viernes",
        dayLabel: "Viernes",
        name: "MR 100 Tiramisù",
        desc: "100 sabores de tiramisú.",
        address: "Via dei Sediari, 11/12",
        rating: 4.7,
        mapsUrl: "https://maps.google.com/?q=MR+100+Tiramisu+Roma",
      },
    ],
    street: [
      {
        day: "martes",
        dayLabel: "Martes / Sábado — Monti",
        name: "La Boccaccia",
        desc: "Pizza al taglio por peso.",
        address: "Via Leonina, 73",
        rating: 4.6,
        mapsUrl: "https://maps.google.com/?q=La+Boccaccia+Via+Leonina+Roma",
      },
      {
        day: "miercoles",
        dayLabel: "Miércoles — Testaccio",
        name: "CasaManco",
        desc: "Pizza alla pala.",
        address: "Mercato di Testaccio, Box 22",
        rating: 4.8,
        mapsUrl: "https://maps.google.com/?q=CasaManco+Testaccio+Roma",
      },
      {
        day: "jueves",
        dayLabel: "Jueves",
        name: "Pastasciutta",
        desc: "Pasta fresca del día en caja.",
        address: "Via delle Grazie, 5",
        rating: 4.6,
        mapsUrl: "https://maps.google.com/?q=Pastasciutta+Via+delle+Grazie+Roma",
      },
      {
        day: "jueves",
        dayLabel: "Jueves",
        name: "Ostevia - Take Away Romano",
        desc: "Pasta para llevar.",
        address: "Via del Mascherino, 64",
        rating: 4.8,
        mapsUrl: "https://maps.app.goo.gl/gEYNsdc7JKgQ9toLA",
      },
      {
        day: "jueves",
        dayLabel: "Jueves",
        name: "Pasta al Sugo",
        desc: "Pasta en caja + tiramisú.",
        address: "Piazza della Città Leonina, 2",
        rating: 4.7,
        mapsUrl: "https://maps.app.goo.gl/xqA66Q5vdHDdALcy8",
      },
      {
        day: "jueves",
        dayLabel: "Jueves — Trastevere",
        name: "Trapizzino",
        desc: "Trapizzino + supplì.",
        address: "Piazza Trilussa, 46",
        rating: 4.5,
        mapsUrl: "https://maps.google.com/?q=Trapizzino+Trilussa+Roma",
      },
      {
        day: "viernes",
        dayLabel: "Viernes",
        name: "All'Antico Vinaio",
        desc: "Schiacciate (focaccias rellenas).",
        address: "Via della Rosetta, 6",
        rating: 4.6,
        mapsUrl: MAPS.search("All'Antico Vinaio Via della Rosetta Roma"),
      },
      {
        day: "viernes",
        dayLabel: "Viernes",
        name: "Forno Campo de' Fiori",
        desc: "Desde 1880; pizza bianca y rossa.",
        address: "Piazza Campo de' Fiori, 22",
        rating: 4.4,
        mapsUrl: "https://maps.google.com/?q=Forno+Campo+de+Fiori+Roma",
      },
      {
        day: "viernes",
        dayLabel: "Viernes",
        name: "Antico Forno Roscioli",
        desc: "Mejores supplì.",
        address: "Via dei Chiavari, 34",
        rating: 4.6,
        mapsUrl: "https://maps.google.com/?q=Antico+Forno+Roscioli+Roma",
      },
      {
        day: "viernes",
        dayLabel: "Viernes",
        name: "Spaghetto Roma al Senato",
        desc: "Pasta fresca al momento.",
        address: "Piazza di S. Luigi de' Francesi, 30",
        rating: 4.8,
        mapsUrl: "https://maps.google.com/?q=Spaghetto+Roma+al+Senato",
      },
    ],
    restaurants: [
      {
        day: "martes",
        dayLabel: "Martes — Monti",
        name: "Il Tettarello",
        desc: "Pizza romana fina, ambiente de barrio.",
        address: "Via dei Capocci, 4",
        walk: "36 m desde casa",
        rating: 4.4,
        mapsUrl: "https://maps.google.com/?cid=16046860355635071366",
      },
      {
        day: "martes",
        dayLabel: "Martes — Monti",
        name: "La Taverna dei Fori Imperiali",
        desc: "Trattoria reputada; reservar.",
        address: "Via della Madonna dei Monti, 9",
        walk: "550 m (7 min)",
        rating: 4.4,
        mapsUrl: "https://maps.google.com/?cid=8046209661515586741",
      },
      {
        day: "martes",
        dayLabel: "Martes — Monti",
        name: "Trieste Pizza",
        desc: "Pizzetas redondas al horno, muy rápido.",
        address: "Via Urbana, 112",
        walk: "140 m (2 min)",
        rating: 4.7,
        mapsUrl: "https://maps.google.com/?cid=2737933372264325648",
      },
      {
        day: "martes",
        dayLabel: "Martes — Monti",
        name: "Osteria della Suburra",
        desc: "Carbonara muy valorada; techo de vigas.",
        address: "Via Urbana, 67",
        walk: "140 m (2 min)",
        rating: 4.1,
        mapsUrl: "https://www.google.com/maps/place//data=!4m2!3m1!19sChIJwREv_a9hLxMRg1iNwBdkUYI",
      },
      {
        day: "martes",
        dayLabel: "Martes — Monti",
        name: "Taverna Urbana",
        desc: "Platos romanos, cerveza y vino.",
        address: "Via Urbana, 137",
        walk: "200 m (3 min)",
        rating: 4.6,
        mapsUrl: "https://www.google.com/maps/place//data=!4m2!3m1!19sChIJ5Qkb0rFhLxMRt2M1vte8uKc",
      },
      {
        day: "martes",
        dayLabel: "Martes — Monti",
        name: "La Carbonara (Monti)",
        desc: "Grafitis en paredes; clásicos romanos.",
        address: "Via Panisperna, 214",
        walk: "350 m (5 min)",
        rating: 4.2,
        mapsUrl: "https://www.google.com/maps/place//data=!4m2!3m1!19sChIJpWSB8rFhLxMRjZpGcb7UB2w",
      },
      {
        day: "martes",
        dayLabel: "Martes — Monti",
        name: "Ai Tre Scalini",
        desc: "Pasta, carne y carta de vinos.",
        address: "Via Panisperna, 251",
        walk: "350 m (5 min)",
        rating: 4.5,
        mapsUrl: "https://maps.google.com/?cid=8986194417230123369",
      },
      {
        day: "miercoles",
        dayLabel: "Miércoles — Campo / Testaccio",
        name: "Osteria da Fortunata",
        desc: "Pasta a mano frente a la ventana.",
        address: "Via del Pellegrino, 11/12",
        walk: "~2,2 km al Coliseo (25–30 min)",
        rating: 4.7,
        mapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Osteria+da+Fortunata+Via+del+Pellegrino+Roma",
      },
      {
        day: "miercoles",
        dayLabel: "Miércoles — Testaccio",
        name: "Piatto Romano",
        desc: "Amatriciana, trippa.",
        address: "Via Giovanni Battista Bodoni, 62",
        walk: "~2,6 km al Coliseo; volver Bus 716 o Tranvía 3",
        rating: 4.5,
        mapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Piatto+Romano+Bodoni+Testaccio+Roma",
      },
      {
        day: "miercoles",
        dayLabel: "Miércoles — Testaccio",
        name: "Da Bucatino",
        desc: "Raciones generosas, ambiente local.",
        address: "Via Luca della Robbia, 84",
        walk: "~2,5 km al Coliseo",
        rating: 4.5,
        mapsUrl: "https://www.google.com/maps/search/?api=1&query=Da+Bucatino+Testaccio+Roma",
      },
      {
        day: "miercoles",
        dayLabel: "Miércoles — Testaccio",
        name: "Felice a Testaccio",
        desc: "Tonnarelli cacio e pepe.",
        address: "Via Mastro Giorgio, 29",
        walk: "~2,4 km al Coliseo",
        rating: 4.3,
        mapsUrl: "https://www.google.com/maps/search/?api=1&query=Felice+a+Testaccio+Roma",
      },
      {
        day: "miercoles",
        dayLabel: "Miércoles — Centro",
        name: "Emma Pizzeria",
        desc: "Pizza redonda de alta calidad.",
        address: "Via del Monte della Farina, 28",
        walk: "~1,8 km al Coliseo",
        rating: 4.3,
        mapsUrl: "https://www.google.com/maps/search/?api=1&query=Emma+Pizzeria+Roma",
      },
      {
        day: "miercoles",
        dayLabel: "Miércoles — Testaccio",
        name: "Flavio al Velavevodetto",
        desc: "RECOMENDADO EXTRA — dentro del Monte Testaccio.",
        address: "Via di Monte Testaccio, 97",
        walk: "~2,5 km al Coliseo",
        rating: 4.6,
        extra: true,
        mapsUrl: "https://www.google.com/maps/search/?api=1&query=Flavio+al+Velavevodetto+Roma",
      },
      {
        day: "miercoles",
        dayLabel: "Miércoles — Campo",
        name: "Roscioli Salumeria con Cucina",
        desc: "RECOMENDADO EXTRA — carbonara top.",
        address: "Via dei Giubbonari, 21",
        walk: "~2,1 km al Coliseo",
        rating: 4.3,
        extra: true,
        mapsUrl: "https://www.google.com/maps/search/?api=1&query=Roscioli+Salumeria+Roma",
      },
      {
        day: "jueves",
        dayLabel: "Jueves — Borgo / Trastevere",
        name: "Pastasciutta",
        desc: "DECIDIDO COMIDA — pasta 4–6€.",
        address: "Via delle Grazie, 5",
        rating: 4.6,
        decided: true,
        mapsUrl: "https://maps.google.com/?q=Pastasciutta+Via+delle+Grazie+Roma",
      },
      {
        day: "jueves",
        dayLabel: "Jueves — Trastevere",
        name: "Da Enzo al 29",
        desc: "Cocina romana honesta; cola; cierra domingos.",
        address: "Via dei Vascellari, 29",
        rating: 4.3,
        mapsUrl: "https://maps.google.com/?q=Da+Enzo+al+29+Roma",
      },
      {
        day: "jueves",
        dayLabel: "Jueves — Trastevere",
        name: "Tonnarello",
        desc: "Familiar, raciones abundantes.",
        address: "Via della Paglia, 1-2-3",
        rating: 4.7,
        mapsUrl: "https://maps.google.com/?q=Tonnarello+Roma",
      },
      {
        day: "jueves",
        dayLabel: "Jueves — Trastevere",
        name: "Trattoria da Teo",
        desc: "Romana + pescado, trufa en temporada.",
        address: "Piazza dei Ponziani, 7A",
        rating: 4.4,
        mapsUrl: "https://maps.google.com/?q=Trattoria+da+Teo+Roma",
      },
      {
        day: "jueves",
        dayLabel: "Jueves — Trastevere",
        name: "Peppo al Cosimato",
        desc: "Pescado de mercado, poco turístico.",
        address: "Via Natale del Grande, 9",
        rating: 4.4,
        mapsUrl: "https://maps.google.com/?q=Peppo+al+Cosimato+Roma",
      },
      {
        day: "jueves",
        dayLabel: "Jueves — Trastevere",
        name: "Pizzeria L'Elementare",
        desc: "Pizza romana baja y crujiente.",
        address: "Via Benedetta, 23",
        rating: 4.4,
        mapsUrl: MAPS.search("Pizzeria L'Elementare Via Benedetta Roma"),
      },
      {
        day: "viernes",
        dayLabel: "Viernes — Centro",
        name: "Restaurantes",
        desc: "Pendiente de decidir.",
        pending: true,
      },
      {
        day: "sabado",
        dayLabel: "Sábado — Monti",
        name: "—",
        desc: "No hay restaurante el sábado.",
        pending: true,
      },
    ],
  },

  priorities: {
    three: "Foro Romano · Palatino · Coliseo · Foros Imperiales · Columna de Trajano · Piazza Venezia · Altare della Patria · San Pedro · Museos Vaticanos/Sixtina · Castel Sant'Angelo · Panteón · Piazza Navona · San Luigi dei Francesi · Sant'Ignazio · Chiesa del Gesù · Fontana di Trevi · Santa Maria del Popolo · Santa Maria Maggiore.",
    two: "Campidoglio · Santa Maria sopra Minerva · Sant'Agnese · Santa Maria in Trastevere · Trastevere · Santa Maria in Cosmedin · Santa Sabina · Giardino degli Aranci · Barrio Judío · Piazza del Popolo · Piazza di Spagna · San Pietro in Vincoli.",
    one: "Circo Massimo · Buco della Serratura · Campo de' Fiori · Largo di Torre Argentina · Ara Pacis.",
  },

  entrancesIntro:
    "Aquí está por dónde entrar a cada monumento con entrada (o cola de seguridad). No son las entradas ya compradas — esas están en Inicio — sino la puerta concreta a la que hay que ir.",

  entrances: [
    {
      title: "Coliseo",
      text: "Sperone Valadier, noreste, frente metro Colosseo (B). Carril “Visitantes con reserva”. Llegar 15–20 min antes (17:00). Sin mochilas +30×30 cm.",
    },
    {
      title: "Foro Romano y Palatino (mismo recinto)",
      text: "Son UNA sola área arqueológica: un ticket, una validación, y os movéis entre Palatino y Foro SIN salir. Entrada recomendada: Via di San Gregorio, 30 (Varco Vignola, junto al Arco de Constantino) → subís primero Palatino y bajáis al Foro por dentro. Evitad Largo della Salara Vecchia (más cola; suele meter más directo al Foro). Otras puertas del mismo recinto: Arco de Tito / Via Sacra, Via del Tulliano, Via del Foro Romano. La puerta de SALIDA sí importa para el siguiente tramo a pie.",
    },
    {
      title: "Museos Vaticanos + Sixtina",
      text: "Única entrada pública: Viale Vaticano, 00120 (lado norte del muro). Metro A Ottaviano, 8–10 min andando. No es la misma puerta que San Pedro (10–15 min rodeando el muro).",
    },
    {
      title: "Basílica de San Pedro",
      text: "Gratis desde la Plaza de San Pedro (cola de seguridad propia). Cúpula de pago 10–15€. Preguntar al guía si el tour incluye paso Sixtina→Basílica sin salir a la calle.",
    },
    {
      title: "Castel Sant'Angelo",
      text: "Entrada única: Lungotevere Castello, 50, junto al Ponte Sant'Angelo.",
    },
    {
      title: "Panteón",
      text: "Entrada por Piazza della Rotonda: la fachada con columnas es la propia entrada.",
    },
  ],

  tips: [
    {
      title: "Documentación",
      text: "Comprobar que los nombres de las entradas nominativas coincidan con DNI/pasaporte.",
    },
    {
      title: "Vestimenta Vaticano y San Pedro",
      text: "Hombros y rodillas cubiertos. La visita guiada en italiano suele ser bastante comprensible.",
    },
    {
      title: "Zonas naturales para comer",
      text: "Monti, Testaccio, Borgo Pio, Trastevere y Barrio Judío / Campo de' Fiori.",
    },
    {
      title: "Foro / Palatino (miércoles)",
      text: "Mismo recinto: no salís entre Palatino y Foro. Maps engaña dentro; lo que importa es por qué puerta SALÍS hacia Foros Imperiales / Venezia.",
    },
  ],

  apps: [
    {
      name: "ATAC Roma",
      desc: "App oficial de buses, tranvía y metro: tiempos reales, planificador y billetes digitales. Imprescindible si usáis transporte.",
      recommend: true,
      platforms: "Android · iOS",
    },
    {
      name: "Google Maps (offline)",
      desc: "Descargad el mapa de Roma antes de salir. Es la base para caminar y para los botones de esta guía.",
      recommend: true,
      platforms: "Android · iOS",
    },
    {
      name: "Google Translate (offline)",
      desc: "Descargad italiano + español. Útil en menús, taquillas y si se pierde alguna palabra del tour del Vaticano.",
      recommend: true,
      platforms: "Android · iOS",
    },
    {
      name: "Trenitalia",
      desc: "Leonardo Express y trenes. Tap&Tap también vale en el torno, pero la app sirve para horarios y Minigruppi.",
      recommend: true,
      platforms: "Android · iOS",
    },
    {
      name: "Rick Steves Audio Europe",
      desc: "Audioguías gratis y sin anuncios: Coliseo, Foro, Panteón, San Pedro e intro a Museos Vaticanos. Solo en inglés.",
      recommend: true,
      platforms: "Android · iOS",
    },
    {
      name: "izi.TRAVEL",
      desc: "Guías de museos y locales, con varias rutas en español. Buena para Trastevere y el centro histórico.",
      recommend: true,
      platforms: "Android · iOS",
    },
    {
      name: "Nasoni / Drinking Fountains",
      desc: "Mapa de las fuentes gratuitas de agua potable (nasoni). Roma es la ciudad ideal para ir con botella.",
      recommend: true,
      platforms: "Android · iOS (buscar “nasoni” o “drinking fountains Rome”)",
    },
    {
      name: "Google Arts & Culture",
      desc: "Repasar Capilla Sixtina y Museos Vaticanos en alta resolución antes o después de la visita.",
      recommend: false,
      platforms: "Android · iOS",
    },
    {
      name: "MyColosseum",
      desc: "Oficial del PArCo. Prescindible: vuestra entrada Tiqets ya lleva audioguía; reseñas en español flojas y GPS poco fiable.",
      recommend: false,
      platforms: "Android · iOS",
    },
    {
      name: "iWander",
      desc: "Audioguías a medida (incluye español), offline. 30 min gratis al registrarse; el resto de pago. Alternativa moderna a Rick Steves si queréis español.",
      recommend: false,
      platforms: "Android · iOS",
    },
  ],

  trains: {
    intro:
      "Leonardo Express Fiumicino↔Termini, 32 min, andenes 23–24 en Termini (en Fiumicino suele salir de vías 2 o 3), cada 15 min. 14€/persona. Desde casa: ~11 min a Termini + 10–15 min logística. Minigruppi 40€ si sois 4.",
    purchase:
      "trenitalia.com, app, taquillas, Tap&Tap en torno ‘Gate Leonardo’. Cambios gratis si compráis antes.",
    fromPlane: {
      title: "Del avión al Leonardo Express",
      subtitle: "Martes 15 · Paso a paso en Fiumicino",
      steps: [
        {
          title: "Salir de la terminal (Llegadas)",
          text: "Sigue el flujo hacia la salida y recogida de equipajes (Baggage Claim / Uscita). Como no lleváis maletas en bodega, pasad de largo las cintas y salid por las puertas automáticas a la zona pública de Llegadas.",
        },
        {
          title: "Seguir los carteles del tren",
          text: "Nada más salir a la zona pública, mirad arriba: carteles amarillos brillantes con icono de tren o “Stazione Ferroviaria / Train”. El aeropuerto está unido a la estación por pasillos internos. Subid escaleras mecánicas o ascensor a la planta superior y seguid las pasarelas cubiertas con cintas. Hay carteles cada pocos metros.",
        },
        {
          title: "Estación y billete (14 €/persona)",
          text: "Tras ~5–7 min llegáis al vestíbulo de la estación. Opciones:",
          bullets: [
            "La más rápida — Tap & Go: no compréis billete. En los tornos pasad móvil o tarjeta contactless; cobra 14 €. Si vais dos, cada uno con su móvil/tarjeta.",
            "Máquinas Trenitalia (rojas/grises): pantalla en español; Fiumicino Aeroporto → Roma Termini; tarjeta o efectivo.",
            "Taquilla o Tabacchi junto a los tornos: billete en mano.",
          ],
        },
        {
          title: "¿Hay que validar? (muy importante)",
          text: "Según cómo compréis:",
          bullets: [
            "Tap & Go en el torno: NO validar. El torno registra la entrada.",
            "Billete digital de máquina (con hora): ya viene pre-validado; solo escanead el QR en el torno. No hace falta máquina de sellado.",
            "Billete de papel sin hora (estanco): SÍ obligatorio sellar en las maquinitas verdes/grises ovaladas antes de la vía. Sin sellar, multa de +50 €.",
          ],
        },
        {
          title: "Subir al tren correcto",
          text: "El Leonardo Express suele salir de las vías 2 o 3 (Binario 2 / 3). Mirad el panel del próximo tren a Roma Termini: es el directo rojo y blanco, sin paradas. Subid, dejad la mochila en el maletero y en 32 min exactos llegáis a Termini.",
        },
      ],
    },
    arrival: {
      date: "Martes 15",
      label: "Ida (Fiumicino → Termini → casa)",
      options: [
        { dep: "17:53", arr: "18:25", home: "~18:36", recommended: false },
        { dep: "18:08", arr: "18:40", home: "~18:51", recommended: true },
        { dep: "18:23", arr: "18:55", home: "~19:06", recommended: false },
      ],
    },
    departure: {
      date: "Sábado 19",
      label: "Vuelta (casa → Termini → Fiumicino)",
      flight: "Vuelo ROM 12:35 → VAL 14:45",
      options: [
        {
          leaveHome: "09:10–09:15",
          termini: "~09:25",
          train: "09:35",
          fiumicino: "10:07",
          recommended: true,
        },
        {
          leaveHome: "09:25–09:30",
          termini: "~09:40",
          train: "09:50",
          fiumicino: "10:22",
          recommended: false,
        },
        {
          leaveHome: "09:40–09:45",
          termini: "~09:55",
          train: "10:05",
          fiumicino: "10:37",
          recommended: false,
        },
      ],
    },
  },

  metro: [
    {
      title: "Casa → Cavour (línea B)",
      text: "Estación más cercana a Via dei Capocci, 86: Cavour (línea B), 3–5 min andando — más cerca que la entrada de metro de Termini.",
    },
    {
      title: "Casa → Vaticano (Ottaviano)",
      text: "Cavour → Termini (cambio a línea A) → Ottaviano. ~20–25 min en metro + 8–10 min andando hasta la entrada de los museos ≈ 30–35 min puerta a puerta.",
    },
    {
      title: "Casa → Piazza del Popolo (Flaminio)",
      text: "Mismo cambio en Termini, 4 paradas más en línea A hasta Flaminio. ~15–20 min en metro + 2 min andando ≈ 20–25 min puerta a puerta.",
    },
    {
      title: "Trastevere",
      text: "El metro NO llega a Trastevere. Alternativas: tranvía 8 (metro B hasta Piramide, luego tranvía hasta Belli/Mastai, ~25–30 min), autobús H directo desde Termini (parada Via Manara, ~20 min), o andar 20–25 min desde Castel Sant'Angelo (como el jueves).",
    },
  ],

  metroRoutes: [
    {
      id: "monti-vaticano",
      title: "Monti → Vaticano (paso a paso)",
      subtitle: "Desde Via dei Capocci hasta Ottaviano / San Pedro",
      steps: [
        "Camina a Metro Cavour (línea B, azul), 3–5 min desde casa.",
        "Línea B: súbete dirección Rebibbia o Jonio y viaja solo 1 parada hasta Termini.",
        "Transbordo en Termini: no salgas de los tornos. Sigue los carteles naranjas de Línea A por los pasillos subterráneos.",
        "Línea A: coge el metro dirección Battistini.",
        "Bájate en Ottaviano (6 paradas desde Termini): la mejor para Plaza de San Pedro / Basílica y Museos Vaticanos (8–10 min andando a la entrada de los museos).",
      ],
    },
    {
      id: "popolo-casa",
      title: "Piazza del Popolo → casa (paso a paso)",
      subtitle: "Vuelta a Via dei Capocci, 86",
      steps: [
        "Entra al metro en Flaminio (línea A, naranja), justo al lado de Piazza del Popolo. Pasa el móvil o la tarjeta por el torno.",
        "Línea A: súbete dirección Anagnina.",
        "Viaja 4 paradas y bájate en Termini.",
        "No hagas transbordo a la línea B: sal a pie de Termini. ~7–8 min / ~600 m bajando por Via Cavour y girando a Via dei Capocci, 86. Es la opción más rápida.",
      ],
    },
  ],
};

/* Resolver mapsUrl en paradas sin enlace */
GUIDE.days.forEach((day) => {
  day.sections.forEach((sec) => {
    sec.stops.forEach((stop) => {
      if (!stop.mapsUrl && stop.title && !stop.pending) {
        stop.mapsUrl = MAPS.search(stop.title.replace(/\s*\(.*\)/, ""));
      }
    });
  });
});

if (typeof globalThis !== "undefined") {
  globalThis.GUIDE = GUIDE;
  globalThis.MAPS = MAPS;
}
if (typeof module !== "undefined") module.exports = { GUIDE, MAPS };
